### PR TITLE
Update CLI for `kobra` and `kobrac` commands

### PR DESCRIPTION
**Pull request by jadengore**
When a user runs `kobra` like so:

`kobra hello-world.ks`

It will pipe the stdout to Node and execute the Kobrascript program.

When a user runs `kobrac` like so:

`kobrac hello-world.ks`

It will print the transpiled code to the terminal.

This is for the 2.1.0 release. Future work will include a REPL for Kobrascript and writing compiled files to the filesystem.

### CODE REVIEW

**Comment by jadengore** [comment]
Also @AuthorOfTheSurf, if you could hold off on the merge there's one more baby change to the PR I'm going to add. Check the diff when I'm done.

**Comment by jadengore** [comment]
OK, we were still checking for blueprint files. Also we were getting errors whenever we ran with no args to see commands, so I moved the extension check into the arg length conditional. Other than that we are good to go :+1: :shipit:

**Comment by AuthorOfTheSurf** [comment]
I always check the diff.

**Comment by jadengore** [comment]
:shipit:

**Pull request merged**
